In [8]:
import numpy as np
import pandas as pd

In [ ]:
#combination of series is known as data frame.
data = {
    'Name' : ['John', 'Piyush', 'Shyam', 'Ram', 'Krishna'],
    'Age' : [23,43,22,34,64],
    'City' : ['New york', 'paris','jaipur','kashmir','udaipur'],
    'salary' : [60000,70000,15000,120000,78000]
}
pd.DataFrame(data)

      Name  Age      City  salary
0     John   23  New york   60000
1   Piyush   43     paris   70000
2    Shyam   22    jaipur   15000
3      Ram   34   kashmir  120000
4  Krishna   64   udaipur   78000

In [53]:
data_list = [
    [ 'John', 28, 'New York', 65000], 
    [ 'Anna', 34, 'Paris', 70000], 
    ['Peter', 29, 'Berlin', 62000], 
    [ 'Linda', 42, 'London', 85000]
]

columns = ['Name','Age','City','salary']
df = pd.DataFrame(data_list,columns=columns)
df

    Name  Age      City  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [29]:
df['Name']
df[['Name',
   'Age']]

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [30]:
df['Designitation']=['Employee','HR',"manager",'PA']

In [31]:
df

    Name  Age      City  salary Designitation
0   John   28  New York   65000      Employee
1   Anna   34     Paris   70000            HR
2  Peter   29    Berlin   62000       manager
3  Linda   42    London   85000            PA

In [51]:
## Remove columns
df.drop('Name',axis = 1, inplace=True)

In [52]:
df

   Age      City  salary
0   28  New York   65000
1   34     Paris   70000
2   29    Berlin   62000
3   42    London   85000

In [57]:
df.loc[[0,1]]
df.iloc[3]

Name       Linda
Age           42
City      London
salary     85000
Name: 3, dtype: object

## subset of rows and columns

In [59]:
df.loc[[0,1]][['City','salary']]

       City  salary
0  New York   65000
1     Paris   70000

In [60]:
df.loc[[0,1]][['Name','Age']]

   Name  Age
0  John   28
1  Anna   34

## Conditional selection

In [64]:
df[df['Age']>30]

    Name  Age    City  salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [67]:
df[(df['Age']>30)& (df['City']=='Paris')]

   Name  Age   City  salary
1  Anna   34  Paris   70000