In [23]:
import numpy as np
import pandas as pd

In [24]:
data = { 'Category' : ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'], 
          'Store' : ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'], 
          'Sales': [100, 200, 150, 250, 120, 180, 200, 300], 
          'Quantity': [10, 15, 12, 18, 8, 20, 15, 25], 
          'Date': pd. date_range('2023-01-01', periods=8)
}
df = pd. DataFrame (data)

In [25]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [10]:
# group by categeory and calculate the sum of sales.
cat = df.groupby('Category')

for i, v in cat:
    print(i)
    print(v)

A
  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
2        A    S2    150        12 2023-01-03
4        A    S1    120         8 2023-01-05
6        A    S2    200        15 2023-01-07
B
  Category Store  Sales  Quantity       Date
1        B    S1    200        15 2023-01-02
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06
7        B    S1    300        25 2023-01-08

In [12]:
cat = df.groupby('Category')['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [15]:
#categoary of multiple data 
cat = df.groupby(['Category','Store'])['Sales'].sum()
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

### Aggrigation

In [16]:
df['Sales'].mean()

np.float64(187.5)

In [17]:
df['Sales'].median()

np.float64(190.0)

In [18]:
df['Sales'].mode()

0    200
Name: Sales, dtype: int64

In [19]:
df['Sales'].max()

np.int64(300)

In [20]:
df['Sales'].min()

np.int64(100)

In [27]:
df['Sales'].agg(['sum','mean','median','max','std','count'])

sum       1500.000000
mean       187.500000
median     190.000000
max        300.000000
std         66.062741
count        8.000000
Name: Sales, dtype: float64

# Pivot table

In [ ]:
data = { 'Date' : pd. date_range( '2023-01-01', periods=20), 
         'Product' : ['A', 'B', 'C', 'D'] * 5,
         'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South' ],
        'Sales': np. random. randint(100, 1000, 20), 
        'Units': np. random. randint(10, 100, 20), 
        'Rep' : ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice' ] }

df = pd. DataFrame (data)

df['Month'] = df['Date'].dt. month_name ( ) 
df ['Quarter' ] = 'Q' + df ['Date' ] .dt. quarter. astype(str)
df
## Aggrigation use pivote tables to finding mean mode and median

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    598     63   John  January      Q1
1  2023-01-02       B   West    620     70   Mary  January      Q1
2  2023-01-03       C  North    128     21    Bob  January      Q1
3  2023-01-04       D  South    856     76  Alice  January      Q1
4  2023-01-05       A   East    426     97   John  January      Q1
5  2023-01-06       B   West    504     32   Mary  January      Q1
6  2023-01-07       C  North    112     18    Bob  January      Q1
7  2023-01-08       D  South    191     76  Alice  January      Q1
8  2023-01-09       A   East    486     50   John  January      Q1
9  2023-01-10       B   West    501     28   Mary  January      Q1
10 2023-01-11       C  North    474     91    Bob  January      Q1
11 2023-01-12       D  South    934     18  Alice  January      Q1
12 2023-01-13       A   East    852     10   John  January      Q1
13 2023-01-14       B   West    572     80   Mary  January      Q1
14 2023-01-15       C  North    578     32    Bob  January      Q1
15 2023-01-16       D  South    811     19  Alice  January      Q1
16 2023-01-17       A   East    492     69   John  January      Q1
17 2023-01-18       B   West    686     58   Mary  January      Q1
18 2023-01-19       C  North    244     97    Bob  January      Q1
19 2023-01-20       D  South    263     34  Alice  January      Q1

In [31]:
pd.pivot_table(df,values='Sales',index='Region',columns='Product',aggfunc='median')

Product      A      B      C      D
Region
East     492.0    NaN    NaN    NaN
North      NaN    NaN  244.0    NaN
South      NaN    NaN    NaN  811.0
West       NaN  572.0    NaN    NaN

In [32]:
pd.pivot_table(df,values=['Sales','Units'],index='Region',columns='Product',aggfunc='median')

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     492.0    NaN    NaN    NaN  63.0   NaN   NaN   NaN
North      NaN    NaN  244.0    NaN   NaN   NaN  32.0   NaN
South      NaN    NaN    NaN  811.0   NaN   NaN   NaN  34.0
West       NaN  572.0    NaN    NaN   NaN  58.0   NaN   NaN

# cross tabs

In [ ]:
pd.crosstab(df['Region'],df['Product'])
# cross tabs are used to finds the number of counts in the table

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0