In [1]:
import numpy as np
import pandas as pd

In [4]:
Employees = pd.DataFrame({
    'EMPLOYEE_ID' : [1,2,3,4,5],
    'NAME' : ['Ram', 'Shyam', 'Dheeraj', 'Piyush', 'Ajay'],
    'AGE' : [22,32,21,28,32],
    'DEPARTMENT' : ['HR', 'IT', 'FINANCE', 'MARKETING', 'PA'],
})

# DATA FRAME 2 SALARY INFORMATION.
salaries = pd.DataFrame({
    'EMPLOYEE_ID' : [1,2,3,6,7],
     'SALARY' : [60000,80000,45000,56000,90000],
     'BONUS' : [5000,3100,11000,15000,8000]
    
})

In [6]:
Employees

   EMPLOYEE_ID     NAME  AGE DEPARTMENT
0            1      Ram   22         HR
1            2    Shyam   32         IT
2            3  Dheeraj   21    FINANCE
3            4   Piyush   28  MARKETING
4            5     Ajay   32         PA

In [7]:
salaries

   EMPLOYEE_ID  SALARY  BONUS
0            1   60000   5000
1            2   80000   3100
2            3   45000  11000
3            6   56000  15000
4            7   90000   8000

In [12]:
pd.merge(Employees,salaries,on='EMPLOYEE_ID' , how='inner')

   EMPLOYEE_ID     NAME  AGE DEPARTMENT  SALARY  BONUS
0            1      Ram   22         HR   60000   5000
1            2    Shyam   32         IT   80000   3100
2            3  Dheeraj   21    FINANCE   45000  11000

In [13]:
pd.merge(Employees,salaries,on='EMPLOYEE_ID' , how='outer')

   EMPLOYEE_ID     NAME   AGE DEPARTMENT   SALARY    BONUS
0            1      Ram  22.0         HR  60000.0   5000.0
1            2    Shyam  32.0         IT  80000.0   3100.0
2            3  Dheeraj  21.0    FINANCE  45000.0  11000.0
3            4   Piyush  28.0  MARKETING      NaN      NaN
4            5     Ajay  32.0         PA      NaN      NaN
5            6      NaN   NaN        NaN  56000.0  15000.0
6            7      NaN   NaN        NaN  90000.0   8000.0

In [14]:
pd.merge(Employees,salaries,on='EMPLOYEE_ID' , how='left')

   EMPLOYEE_ID     NAME  AGE DEPARTMENT   SALARY    BONUS
0            1      Ram   22         HR  60000.0   5000.0
1            2    Shyam   32         IT  80000.0   3100.0
2            3  Dheeraj   21    FINANCE  45000.0  11000.0
3            4   Piyush   28  MARKETING      NaN      NaN
4            5     Ajay   32         PA      NaN      NaN

In [15]:
pd.merge(Employees,salaries,on='EMPLOYEE_ID' , how='right')

   EMPLOYEE_ID     NAME   AGE DEPARTMENT  SALARY  BONUS
0            1      Ram  22.0         HR   60000   5000
1            2    Shyam  32.0         IT   80000   3100
2            3  Dheeraj  21.0    FINANCE   45000  11000
3            6      NaN   NaN        NaN   56000  15000
4            7      NaN   NaN        NaN   90000   8000

## concartination

In [16]:
pd.concat([Employees,salaries])

   EMPLOYEE_ID     NAME   AGE DEPARTMENT   SALARY    BONUS
0            1      Ram  22.0         HR      NaN      NaN
1            2    Shyam  32.0         IT      NaN      NaN
2            3  Dheeraj  21.0    FINANCE      NaN      NaN
3            4   Piyush  28.0  MARKETING      NaN      NaN
4            5     Ajay  32.0         PA      NaN      NaN
0            1      NaN   NaN        NaN  60000.0   5000.0
1            2      NaN   NaN        NaN  80000.0   3100.0
2            3      NaN   NaN        NaN  45000.0  11000.0
3            6      NaN   NaN        NaN  56000.0  15000.0
4            7      NaN   NaN        NaN  90000.0   8000.0

In [19]:
pd.concat([Employees,salaries], axis=1)

   EMPLOYEE_ID     NAME  AGE DEPARTMENT  EMPLOYEE_ID  SALARY  BONUS
0            1      Ram   22         HR            1   60000   5000
1            2    Shyam   32         IT            2   80000   3100
2            3  Dheeraj   21    FINANCE            3   45000  11000
3            4   Piyush   28  MARKETING            6   56000  15000
4            5     Ajay   32         PA            7   90000   8000

# joining two data frames

In [21]:
df1 = pd. DataFrame ( { 
    'name': [ 'Alice', 'Bob', 'Charlie' ]
  }
    , index=[1, 2, 3])
# second data frames
df2 = pd.DataFrame({
    'Score' : [85,98,78]
}, index = [2,3,4])

In [22]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [23]:
df2

   Score
2     85
3     98
4     78

In [26]:
df1.join(df2, how='outer')

      name  Score
1    Alice    NaN
2      Bob   85.0
3  Charlie   98.0
4      NaN   78.0

In [28]:
df2.join(df1, how='outer')

   Score     name
1    NaN    Alice
2   85.0      Bob
3   98.0  Charlie
4   78.0      NaN

In [29]:
df1.join(df2, how='inner')

      name  Score
2      Bob     85
3  Charlie     98